import {
  BadRequestException,
  ConflictException,
  Controller,
  Get,
  Header,
  NotFoundException,
  Put,
  Req,
  Res,
} from '@nestjs/common';
import { ApiExcludeController } from '@nestjs/swagger';
import type { Request, Response } from 'express';
import { createReadStream, existsSync, mkdirSync, statSync, writeFileSync } from 'fs';
import { dirname, join, normalize, resolve, sep } from 'path';
import { Public } from '../../common/decorators/public.decorator';
import { AppConfigService } from '../../config/app-config.service';

/** What a browser is told a file is, from its extension. */
const CONTENT_TYPES: Record<string, string> = {
  jpg: 'image/jpeg',
  jpeg: 'image/jpeg',
  jpe: 'image/jpeg',
  // Chrome on Windows writes ordinary JPEGs under this extension. Serving it
  // as octet-stream makes the browser download the photograph instead of
  // showing it, which reads as "the upload did not work".
  jfif: 'image/jpeg',
  pjpeg: 'image/jpeg',
  png: 'image/png',
  apng: 'image/apng',
  webp: 'image/webp',
  gif: 'image/gif',
  bmp: 'image/bmp',
  avif: 'image/avif',
  heic: 'image/heic',
  heif: 'image/heif',
  tif: 'image/tiff',
  tiff: 'image/tiff',
  mp4: 'video/mp4',
  m4v: 'video/mp4',
  mov: 'video/quicktime',
  webm: 'video/webm',
  '3gp': 'video/3gpp',
  pdf: 'application/pdf',
};

/**
 * The storage the mock provider has been pointing at all along.
 *
 * `presign` returned `http://localhost:3000/mock-storage/...` and said uploads
 * "work end-to-end locally without AWS" — but nothing ever served that URL. The
 * browser PUT the file, got a 404 from the router, and the uploader reported
 * "That photo could not be uploaded". Every upload in every deployment not
 * configured for S3 failed at exactly that point: the agent's mandatory biodata
 * photograph, the support attachment, the album, the vendor's portfolio.
 *
 * It never showed up in a test because the suites post a literal
 * `https://cdn.example.com/...` and never PUT anything anywhere — the one step
 * that was broken was the one step nothing exercised.
 *
 * Registered only when the provider is `mock`. With `MEDIA_STORAGE_PROVIDER=s3`
 * the browser PUTs to a real presigned S3 URL and these routes do not exist.
 */
@ApiExcludeController()
@Controller('mock-storage')
export class MockStorageController {
  constructor(private readonly cfg: AppConfigService) {}

  private pathFor(key: string): string {
    const root = resolve(this.cfg.media.mockStorageDir);
    // The key is generated by the platform, but it arrives back from the
    // client, so it is re-checked here rather than trusted. `..` in it would
    // otherwise write anywhere the process can reach.
    const target = resolve(join(root, normalize(key)));
    if (!target.startsWith(root + sep) && target !== root) {
      throw new BadRequestException('Bad object key');
    }
    return target;
  }

  @Public()
  // Express 4's wildcard, which is what Nest 10 is running. The named form
  // (`*key`) is Express 5 syntax and matches nothing here — it registered a
  // route that could never fire, so the PUT 404'd exactly as it did when there
  // was no route at all.
  @Put('*')
  put(@Req() req: Request & { rawBody?: Buffer }) {
    const objectKey = req.params[0] ?? '';
    const body = req.rawBody ?? (Buffer.isBuffer(req.body) ? req.body : null);
    if (!body || body.length === 0) {
      throw new BadRequestException('Nothing to store');
    }
    if (body.length > this.cfg.media.maxFileSizeBytes) {
      throw new BadRequestException('That file is too large');
    }

    const target = this.pathFor(objectKey);
    /*
     * Write once, never replace.
     *
     * This route cannot be authenticated: with the real provider the browser
     * PUTs to a presigned S3 URL carrying its own auth and sends no bearer
     * token, so requiring one here would break every upload on the default
     * provider. What it can refuse is overwriting. Every media URL the API
     * hands out -- a profile photograph, a support-case attachment, the
     * evidence a provider files on a booking -- is also its own write address,
     * so without this anyone who had seen one could silently replace the bytes
     * behind it while the row, the history and the case all went on pointing at
     * the same URL (council review). presign mints a fresh random key per
     * upload, so a legitimate client never PUTs the same key twice.
     */
    if (existsSync(target)) {
      throw new ConflictException('That object already exists');
    }
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, body);
    // S3 answers a successful PUT with an empty 200, so this does too — a
    // client written against the real provider must not need a second path.
    return '';
  }

  @Public()
  @Get('*')
  @Header('Cache-Control', 'public, max-age=3600')
  get(@Req() req: Request, @Res() res: Response) {
    const objectKey = req.params[0] ?? '';
    const target = this.pathFor(objectKey);
    if (!existsSync(target) || !statSync(target).isFile()) {
      throw new NotFoundException('No such object');
    }

    const extension = target.split('.').pop()?.toLowerCase() ?? '';
    res.setHeader('Content-Type', CONTENT_TYPES[extension] ?? 'application/octet-stream');
    createReadStream(target).pipe(res);
  }
}
